import { Response } from '../types';
import { IColumn } from '../../../../shared/ui/Textarea/types';

export const response: Response[] = [
  {
    id: '37890606',
    name: 'Иван',
    lastName: 'Иванов',
    gender: 'M',
    dateOfBirth: '18.12.1999',
    email: 'tienlapspktnd@gmail.com',
    phone: '+79038403153',
    registerChannel: 'Сайт',
    participationConfirm: false,
    emailConfirm: false,
    phoneConfirm: true,
    checks: 1,
    prizes: 0,
  },
  {
    id: '12345678',
    name: 'Петр',
    lastName: 'Петров',
    gender: 'M',
    dateOfBirth: '01.01.1985',
    email: 'petr.petrov@example',
    phone: '+79123456789',
    registerChannel: 'Соцсети',
    participationConfirm: true,
    emailConfirm: true,
    phoneConfirm: true,
    checks: 0,
    prizes: 0,
  },
  {
    id: '87654321',
    name: 'Мария',
    lastName: 'Сидорова',
    gender: 'Ж',
    dateOfBirth: '15.05.1992',
    email: 'maria.sidorov@example',
    phone: '+79991112222',
    registerChannel: 'Реклама',
    participationConfirm: false,
    emailConfirm: true,
    phoneConfirm: false,
    checks: 1,
    prizes: 0,
  },
  {
    id: '98765432',
    name: 'Сергей',
    lastName: 'Смирнов',
    gender: 'M',
    dateOfBirth: '22.11.2000',
    email: 'sergey.smirnov@example',
    phone: '+79112223333',
    registerChannel: 'Сайт',
    participationConfirm: true,
    emailConfirm: false,
    phoneConfirm: true,
    checks: 0,
    prizes: 1,
  },
  {
    id: '11223344',
    name: 'Анна',
    lastName: 'Кузнецова',
    gender: 'Ж',
    dateOfBirth: '08.08.1988',
    email: 'anna.kuznecova@example',
    phone: '+79223334444',
    registerChannel: 'Рекомендация',
    participationConfirm: true,
    emailConfirm: true,
    phoneConfirm: true,
    checks: 1,
    prizes: 0,
  },
  {
    id: '44332211',
    name: 'Дмитрий',
    lastName: 'Попов',
    gender: 'M',
    dateOfBirth: '10.10.1995',
    email: 'dmitry.popov@example',
    phone: '+79334445555',
    registerChannel: 'Сайт',
    participationConfirm: false,
    emailConfirm: false,
    phoneConfirm: false,
    checks: 0,
    prizes: 0,
  },
  {
    id: '55667788',
    name: 'Елена',
    lastName: 'Соколова',
    gender: 'Ж',
    dateOfBirth: '28.02.1990',
    email: 'elena.sokolova@example',
    phone: '+79445556666',
    registerChannel: 'Соцсети',
    participationConfirm: true,
    emailConfirm: true,
    phoneConfirm: true,
    checks: 1,
    prizes: 0,
  },
  {
    id: '88776655',
    name: 'Алексей',
    lastName: 'Лебедев',
    gender: 'M',
    dateOfBirth: '12.06.2002',
    email: 'alexey.lebedev@example',
    phone: '+79556667777',
    registerChannel: 'Реклама',
    participationConfirm: false,
    emailConfirm: true,
    phoneConfirm: false,
    checks: 0,
    prizes: 0,
  },
  {
    id: '77889900',
    name: 'Ольга',
    lastName: 'Козлова',
    gender: 'Ж',
    dateOfBirth: '25.09.1987',
    email: 'olga.kozlova@example',
    phone: '+79667778888',
    registerChannel: 'Рекомендация',
    participationConfirm: true,
    emailConfirm: false,
    phoneConfirm: true,
    checks: 1,
    prizes: 1,
  },
  {
    id: '13579135',
    name: 'Андрей',
    lastName: 'Новиков',
    gender: 'M',
    dateOfBirth: '07.04.1998',
    email: 'andrey.novikov@example',
    phone: '+79778889999',
    registerChannel: 'Сайт',
    participationConfirm: false,
    emailConfirm: true,
    phoneConfirm: false,
    checks: 0,
    prizes: 0,
  },
  {
    id: '24680246',
    name: 'Светлана',
    lastName: 'Морозова',
    gender: 'Ж',
    dateOfBirth: '19.03.1989',
    email: 'svetlana.morozova@example',
    phone: '+79889990000',
    registerChannel: 'Соцсети',
    participationConfirm: true,
    emailConfirm: true,
    phoneConfirm: true,
    checks: 1,
    prizes: 0,
  },
  {
    id: '12121212',
    name: 'Василий',
    lastName: 'Васильев',
    gender: 'M',
    dateOfBirth: '05.07.2001',
    email: 'vasily.vasilyev@example',
    phone: '+79111112222',
    registerChannel: 'Реклама',
    participationConfirm: false,
    emailConfirm: false,
    phoneConfirm: true,
    checks: 0,
    prizes: 0,
  },
  {
    id: '34343434',
    name: 'Евгений',
    lastName: 'Фёдоров',
    gender: 'M',
    dateOfBirth: '16.09.2003',
    email: 'evgeny.fedorov@example',
    phone: '+79333334444',
    registerChannel: 'Сайт',
    participationConfirm: true,
    emailConfirm: false,
    phoneConfirm: true,
    checks: 0,
    prizes: 1,
  },
  {
    id: '45454545',
    name: 'Наталья',
    lastName: 'Волкова',
    gender: 'Ж',
    dateOfBirth: '02.03.1991',
    email: 'natalia.volkova@example',
    phone: '+79444445555',
    registerChannel: 'Соцсети',
    participationConfirm: false,
    emailConfirm: true,
    phoneConfirm: false,
    checks: 1,
    prizes: 0,
  }, {
    id: '11223344',
    name: 'Анна',
    lastName: 'Кузнецова',
    gender: 'Ж',
    dateOfBirth: '08.08.1988',
    email: 'anna.kuznecova@example',
    phone: '+79223334444',
    registerChannel: 'Рекомендация',
    participationConfirm: true,
    emailConfirm: true,
    phoneConfirm: true,
    checks: 1,
    prizes: 0,
  },
  {
    id: '44332211',
    name: 'Дмитрий',
    lastName: 'Попов',
    gender: 'M',
    dateOfBirth: '10.10.1995',
    email: 'dmitry.popov@example',
    phone: '+79334445555',
    registerChannel: 'Сайт',
    participationConfirm: false,
    emailConfirm: false,
    phoneConfirm: false,
    checks: 0,
    prizes: 0,
  },
  {
    id: '55667788',
    name: 'Елена',
    lastName: 'Соколова',
    gender: 'Ж',
    dateOfBirth: '28.02.1990',
    email: 'elena.sokolova@example',
    phone: '+79445556666',
    registerChannel: 'Соцсети',
    participationConfirm: true,
    emailConfirm: true,
    phoneConfirm: true,
    checks: 1,
    prizes: 0,
  },
  {
    id: '88776655',
    name: 'Алексей',
    lastName: 'Лебедев',
    gender: 'M',
    dateOfBirth: '12.06.2002',
    email: 'alexey.lebedev@example',
    phone: '+79556667777',
    registerChannel: 'Реклама',
    participationConfirm: false,
    emailConfirm: true,
    phoneConfirm: false,
    checks: 0,
    prizes: 0,
  },
  {
    id: '77889900',
    name: 'Ольга',
    lastName: 'Козлова',
    gender: 'Ж',
    dateOfBirth: '25.09.1987',
    email: 'olga.kozlova@example',
    phone: '+79667778888',
    registerChannel: 'Рекомендация',
    participationConfirm: true,
    emailConfirm: false,
    phoneConfirm: true,
    checks: 1,
    prizes: 1,
  },
  {
    id: '13579135',
    name: 'Андрей',
    lastName: 'Новиков',
    gender: 'M',
    dateOfBirth: '07.04.1998',
    email: 'andrey.novikov@example',
    phone: '+79778889999',
    registerChannel: 'Сайт',
    participationConfirm: false,
    emailConfirm: true,
    phoneConfirm: false,
    checks: 0,
    prizes: 0,
  },
  {
    id: '24680246',
    name: 'Светлана',
    lastName: 'Морозова',
    gender: 'Ж',
    dateOfBirth: '19.03.1989',
    email: 'svetlana.morozova@example',
    phone: '+79889990000',
    registerChannel: 'Соцсети',
    participationConfirm: true,
    emailConfirm: true,
    phoneConfirm: true,
    checks: 1,
    prizes: 0,
  },
  {
    id: '12121212',
    name: 'Василий',
    lastName: 'Васильев',
    gender: 'M',
    dateOfBirth: '05.07.2001',
    email: 'vasily.vasilyev@example',
    phone: '+79111112222',
    registerChannel: 'Реклама',
    participationConfirm: false,
    emailConfirm: false,
    phoneConfirm: true,
    checks: 0,
    prizes: 0,
  },
  {
    id: '34343434',
    name: 'Евгений',
    lastName: 'Фёдоров',
    gender: 'M',
    dateOfBirth: '16.09.2003',
    email: 'evgeny.fedorov@example',
    phone: '+79333334444',
    registerChannel: 'Сайт',
    participationConfirm: true,
    emailConfirm: false,
    phoneConfirm: true,
    checks: 0,
    prizes: 1,
  },
  {
    id: '45454545',
    name: 'Наталья',
    lastName: 'Волкова',
    gender: 'Ж',
    dateOfBirth: '02.03.1991',
    email: 'natalia.volkova@example',
    phone: '+79444445555',
    registerChannel: 'Соцсети',
    participationConfirm: false,
    emailConfirm: true,
    phoneConfirm: false,
    checks: 1,
    prizes: 0,
  },
];

// можно еще в конфиг прописать шириру колонок

export const columns: IColumn<Response>[] = [
  {
    id: 'id',
    name: 'ID',
    type: 'string',
    fixed: true,
  },
  {
    id: 'name',
    name: 'Имя',
    type: 'string',
  },
  {
    id: 'lastName',
    name: 'Фамилия',
    type: 'string',
  },
  {
    id: 'gender',
    name: 'Пол',
    type: 'string',
  },
  {
    id: 'dateOfBirth',
    name: 'День рождения',
    type: 'string',
  },
  {
    id: 'email',
    name: 'Email',
    type: 'string',
  },
  {
    id: 'phone',
    name: 'Телефон',
    type: 'string',
  },
  {
    id: 'registerChannel',
    name: 'Канал регистрации',
    type: 'string',
  },
  {
    id: 'participationConfirm',
    name: 'Участие разрешено',
    type: 'bool',
  },
  {
    id: 'emailConfirm',
    name: 'Email подтвержден',
    type: 'bool',
  },
  {
    id: 'phoneConfirm',
    name: 'Телефон подтвержден',
    type: 'bool',
  },
  {
    id: 'checks',
    name: 'Чеки',
    type: 'string',
  },
  {
    id: 'prizes',
    name: 'Призы',
    type: 'string',
  },
];
